ui <- fluidPage(
  titlePanel("Credit risk"),
  sidebarLayout(
    sidebarPanel(
      tabsetPanel(id = "tabset",
                  tabPanel("one variable",
                           selectInput(inputId = "parametr", 
                                       label = "Choose parametr to analize",
                                       choices = parameters),
                           sliderInput(inputId = "age_range",
                                       label = "Choose age:",
                                       min = 18,
                                       max = 80,
                                       value = c(18,80),
                                       step = 1),
                           selectInput(inputId = "color", 
                                       label = "Choose color",
                                       choices = vector_color),
                           selectInput(inputId = "position", 
                                       label = "Choose position",
                                       choices = vector_position),
                           selectInput(inputId = 'font',
                                       label = 'Choose font',
                                       choices = vector_fonts),
                           numericInput(inputId = "step",
                                        label = "Choose step in age range:",
                                        value = 5),
                           numericInput(inputId = "amount",
                                        label = "Choose step in amount range:",
                                        value = 2000),
                           downloadButton(outputId = 'downloadPlot', label = 'Download Plot')
                  ),
                  tabPanel("two variable",
                           selectInput(inputId = "parametr", 
                                       label = "Choose parametr to analize",
                                       choices = parameters),
                           selectInput(inputId = "parametr2", 
                                       label = "Choose second parametr to analize",
                                       choices = parameters),
                           sliderInput(inputId = "age_range",
                                       label = "Choose age:",
                                       min = 18,
                                       max = 80,
                                       value = c(18,80),
                                       step = 1),
                           selectInput(inputId = "color", 
                                       label = "Choose color",
                                       choices = vector_color),
                           selectInput(inputId = "position", 
                                       label = "Choose position",
                                       choices = vector_position),
                           selectInput(inputId = 'font',
                                       label = 'Choose font',
                                       choices = vector_fonts),
                           numericInput(inputId = "step",
                                        label = "Choose step in age range:",
                                        value = 5),
                           numericInput(inputId = "amount",
                                        label = "Choose step in amount range:",
                                        value = 2000)
                  ))
    ),
    mainPanel(
      plotOutput("plot")
      
    )
  )
)
