ui <- fluidPage(
  column(3, titlePanel("Credit risk"), 
         selectInput(inputId = "parametr", 
                     label = "Choose parametr to analize",
                     choices = parameters),
         selectInput(inputId = "parametr2", 
                     label = "Choose second parametr to analize",
                     choices = parameters),
         sliderInput(inputId = "age_range",
                     label = "Choose age:",
                     min = 18,
                     max = 80,
                     value = c(18,80),
                     step = 1),
         selectInput(inputId = "color", 
                     label = "Choose color",
                     choices = vector_color),
         selectInput(inputId = "position", 
                     label = "Choose position",
                     choices = vector_position),
         selectInput(inputId = 'font',
                     label = 'Choose font',
                     choices = vector_fonts),
         numericInput(inputId = "step",
                      label = "Choose step in age range:",
                      value = 1),
         numericInput(inputId = "amount",
                      label = "Choose step in amount range:",
                      value = 1)),
  
  column(9,tabsetPanel(
    tabPanel("1 variable", plotOutput("one_variable")),
    tabPanel("2 variables", plotOutput("two_variables"))
  )))